import iostream

def main(int argc, char **argv):
    printf("hacking facebook...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    printf("brute-forcing password...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    sleep(0.1)
    printf("...")
    printf("found password: hunter2")
    return 0
